language: python
python: 2.7
env:
 - TOX_ENV=py27
 - TOX_ENV=cover
before_install:
 - pip install --upgrade pip setuptools tox virtualenv
 - if [ "x$TOX_ENV" = 'xcover' ]; then pip install coveralls ; fi
script:
 - tox -e $TOX_ENV
after_success:
 - if [ "x$TOX_ENV" = 'xcover' ]; then coveralls; fi
